In [1]:
import pandas as pd
import  numpy as np

from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split,GridSearchCV
from word2number import w2n

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier



In [2]:
Data=pd.read_csv(r"C:\Users\acer\OneDrive\Desktop\TECHOLAS\A_2_Z_CLASS\5.MACHINE_LEARNING\DATA\synthetic_dataset.csv")
Data

age  salary  experience      score department  gender    education  \
0    56   38392          10   8.159418    Finance  Female          PhD   
1    46   60535           3   0.518486         HR    Male    Bachelors   
2    32   82256           7  62.789441         IT  Female  High School   
3    25   65222          16  19.427395  Marketing    Male      Masters   
4    38   93335          16   7.094092         HR  Female          PhD   
..  ...     ...         ...        ...        ...     ...          ...   
95   59   31802           7  27.396113         HR  Female      Masters   
96   56   38155          10  21.458912    Finance    Male  High School   
97   58   69384           3  37.725908         HR    Male    Bachelors   
98   45   77254          18   3.896313         HR    Male      Masters   
99   24   51918          13  61.825388         IT    Male      Masters   

    projects  hours_worked  rating  promotion  
0          1            31     4.8          0  
1          1            45     3.6          1  
2          2            53     1.0          1  
3          9            33     3.7          0  
4          3            45     2.6          1  
..       ...           ...     ...        ...  
95         6            30     4.8          0  
96         5            27     1.7          0  
97         6            45     1.1          0  
98         1            24     2.1          0  
99         5            25     1.4          1  

[100 rows x 11 columns]

In [3]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   age           100 non-null    int64  
 1   salary        100 non-null    int64  
 2   experience    100 non-null    int64  
 3   score         100 non-null    float64
 4   department    100 non-null    object 
 5   gender        100 non-null    object 
 6   education     100 non-null    object 
 7   projects      100 non-null    int64  
 8   hours_worked  100 non-null    int64  
 9   rating        100 non-null    float64
 10  promotion     100 non-null    int64  
dtypes: float64(2), int64(6), object(3)
memory usage: 8.7+ KB


In [4]:
Data = Data.drop('gender',axis=1)
Data

age  salary  experience      score department    education  projects  \
0    56   38392          10   8.159418    Finance          PhD         1   
1    46   60535           3   0.518486         HR    Bachelors         1   
2    32   82256           7  62.789441         IT  High School         2   
3    25   65222          16  19.427395  Marketing      Masters         9   
4    38   93335          16   7.094092         HR          PhD         3   
..  ...     ...         ...        ...        ...          ...       ...   
95   59   31802           7  27.396113         HR      Masters         6   
96   56   38155          10  21.458912    Finance  High School         5   
97   58   69384           3  37.725908         HR    Bachelors         6   
98   45   77254          18   3.896313         HR      Masters         1   
99   24   51918          13  61.825388         IT      Masters         5   

    hours_worked  rating  promotion  
0             31     4.8          0  
1             45     3.6          1  
2             53     1.0          1  
3             33     3.7          0  
4             45     2.6          1  
..           ...     ...        ...  
95            30     4.8          0  
96            27     1.7          0  
97            45     1.1          0  
98            24     2.1          0  
99            25     1.4          1  

[100 rows x 10 columns]

In [5]:
Data.department.unique()

array(['Finance', 'HR', 'IT', 'Marketing'], dtype=object)

In [6]:
dept_map={'Finance':0,'HR':1,'IT':2,'Marketing':3}
Data['department']=Data['department'].replace(dept_map)
Data

C:\Users\acer\AppData\Local\Temp\ipykernel_14756\1650390700.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Data['department']=Data['department'].replace(dept_map)


age  salary  experience      score  department    education  projects  \
0    56   38392          10   8.159418           0          PhD         1   
1    46   60535           3   0.518486           1    Bachelors         1   
2    32   82256           7  62.789441           2  High School         2   
3    25   65222          16  19.427395           3      Masters         9   
4    38   93335          16   7.094092           1          PhD         3   
..  ...     ...         ...        ...         ...          ...       ...   
95   59   31802           7  27.396113           1      Masters         6   
96   56   38155          10  21.458912           0  High School         5   
97   58   69384           3  37.725908           1    Bachelors         6   
98   45   77254          18   3.896313           1      Masters         1   
99   24   51918          13  61.825388           2      Masters         5   

    hours_worked  rating  promotion  
0             31     4.8          0  
1             45     3.6          1  
2             53     1.0          1  
3             33     3.7          0  
4             45     2.6          1  
..           ...     ...        ...  
95            30     4.8          0  
96            27     1.7          0  
97            45     1.1          0  
98            24     2.1          0  
99            25     1.4          1  

[100 rows x 10 columns]

In [7]:
Data.education.unique()

array(['PhD', 'Bachelors', 'High School', 'Masters'], dtype=object)

In [8]:
edu_map={'Bachelors':0,'High School':1,'Masters':2,'PhD':3}
Data['education']=Data['education'].map(edu_map)
Data

age  salary  experience      score  department  education  projects  \
0    56   38392          10   8.159418           0          3         1   
1    46   60535           3   0.518486           1          0         1   
2    32   82256           7  62.789441           2          1         2   
3    25   65222          16  19.427395           3          2         9   
4    38   93335          16   7.094092           1          3         3   
..  ...     ...         ...        ...         ...        ...       ...   
95   59   31802           7  27.396113           1          2         6   
96   56   38155          10  21.458912           0          1         5   
97   58   69384           3  37.725908           1          0         6   
98   45   77254          18   3.896313           1          2         1   
99   24   51918          13  61.825388           2          2         5   

    hours_worked  rating  promotion  
0             31     4.8          0  
1             45     3.6          1  
2             53     1.0          1  
3             33     3.7          0  
4             45     2.6          1  
..           ...     ...        ...  
95            30     4.8          0  
96            27     1.7          0  
97            45     1.1          0  
98            24     2.1          0  
99            25     1.4          1  

[100 rows x 10 columns]

In [9]:
Data.isna().sum()

age             0
salary          0
experience      0
score           0
department      0
education       0
projects        0
hours_worked    0
rating          0
promotion       0
dtype: int64

In [10]:
x=Data.drop(['promotion'],axis=1)
y=Data['promotion']
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [13]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


# TRAINING MODELS ONE BY ONE

In [26]:
from sklearn.metrics import confusion_matrix, classification_report

# Dictionary of all models
models = {
    "Logistic Regression": LogisticRegression(),
    "Gaussian Naive Bayes": GaussianNB(),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "KNN (k=15)": KNeighborsClassifier(n_neighbors=15),
    "SVM": SVC(random_state=42),
    "Random Forest": RandomForestClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "Gradient Boosting": GradientBoostingClassifier()
}

results=[]
# Loop through all models
for name, model in models.items():
    print(f"\n==============================")
    print(f"Model: {name}")
    print("==============================")

    # Train
    model.fit(X_train, y_train)

    # Predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Scores
    train_score = model.score(X_train, y_train)
    test_score = model.score(X_test, y_test)

    print(f"Train Accuracy: {train_score:.4f}")
    print(f"Test Accuracy: {test_score:.4f}")

    # Confusion Matrix & Classification Report
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_test_pred))

    print("\nTrain Classification Report:")
    print(classification_report(y_train, y_train_pred))

    print("\nTest Classification Report:")
    print(classification_report(y_test, y_test_pred))


    # Append to results
    results.append([
        name,
        train_score, test_score,
    ])


# Create DataFrame
df_results = pd.DataFrame(results, columns=[
    "Model",
    "Train Accuracy", "Test Accuracy"
])





Model: Logistic Regression
Train Accuracy: 0.6250
Test Accuracy: 0.3500

Confusion Matrix:
[[ 7  0]
 [13  0]]

Train Classification Report:
              precision    recall  f1-score   support

           0       0.63      0.92      0.75        48
           1       0.60      0.19      0.29        32

    accuracy                           0.62        80
   macro avg       0.61      0.55      0.52        80
weighted avg       0.62      0.62      0.56        80


Test Classification Report:
              precision    recall  f1-score   support

           0       0.35      1.00      0.52         7
           1       0.00      0.00      0.00        13

    accuracy                           0.35        20
   macro avg       0.17      0.50      0.26        20
weighted avg       0.12      0.35      0.18        20


Model: Gaussian Naive Bayes
Train Accuracy: 0.6375
Test Accuracy: 0.6500

Confusion Matrix:
[[ 0  7]
 [ 0 13]]

Train Classification Report:
              precision    recall 

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib

Train Accuracy: 1.0000
Test Accuracy: 0.3500

Confusion Matrix:
[[ 7  0]
 [13  0]]

Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        48
           1       1.00      1.00      1.00        32

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80


Test Classification Report:
              precision    recall  f1-score   support

           0       0.35      1.00      0.52         7
           1       0.00      0.00      0.00        13

    accuracy                           0.35        20
   macro avg       0.17      0.50      0.26        20
weighted avg       0.12      0.35      0.18        20


Model: AdaBoost
Train Accuracy: 0.8750
Test Accuracy: 0.3500

Confusion Matrix:
[[ 7  0]
 [13  0]]

Train Classification Report:
              precision    recall  f1-score   support

           0       

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib

Train Accuracy: 1.0000
Test Accuracy: 0.6000

Confusion Matrix:
[[ 1  6]
 [ 2 11]]

Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        48
           1       1.00      1.00      1.00        32

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80


Test Classification Report:
              precision    recall  f1-score   support

           0       0.33      0.14      0.20         7
           1       0.65      0.85      0.73        13

    accuracy                           0.60        20
   macro avg       0.49      0.49      0.47        20
weighted avg       0.54      0.60      0.55        20



In [27]:
df_results

Model  Train Accuracy  Test Accuracy
0   Logistic Regression          0.6250           0.35
1  Gaussian Naive Bayes          0.6375           0.65
2         Decision Tree          1.0000           0.35
3            KNN (k=15)          0.4750           0.35
4                   SVM          0.6750           0.35
5         Random Forest          1.0000           0.35
6              AdaBoost          0.8750           0.35
7     Gradient Boosting          1.0000           0.60

In [28]:
model =GaussianNB()
model.fit(X_train,y_train)
train_score=model.score(X_train,y_train)
test_score=model.score(X_test,y_test)

print("The best model is Gaussian Naive Bayes")
print("Train Score:", train_score)
print("Test Score:", test_score)

The best model is Gaussian Naive Bayes
Train Score: 0.6375
Test Score: 0.65


# ✅ Interactive Input

In [13]:

print("Enter the following details to predict promotion:")

age = int(input("Age: "))
salary = int(input("Salary: "))
experience = int(input("Years of Experience: "))
score = float(input("Performance Score (0-100): "))

print("Departments: Finance, HR, IT, Marketing")
department = input("Department: ").strip()
department = dept_map.get(department, 0)  # Default to 0 if unknown


print("Education Levels: Bachelors, High School, Masters, PhD")
education = input("Education: ").strip()
education = edu_map.get(education, 0)

projects = int(input("Number of Projects: "))
hours_worked = int(input("Hours Worked per Week: "))
rating = float(input("Manager Rating (1.0 to 5.0): "))



Enter the following details to predict promotion:


Age:  34
Salary:  45000
Years of Experience:  3
Performance Score (0-100):  4


Departments: Finance, HR, IT, Marketing


Department:  Finance


Education Levels: Bachelors, High School, Masters, PhD


Education:  Bachelors
Number of Projects:  3
Hours Worked per Week:  45
Manager Rating (1.0 to 5.0):  4


In [16]:
# Prepare input for prediction
user_data = np.array([
    age,
    salary,
    experience,
    score,
    department,
    education,
    projects,
    hours_worked,
    rating
]).reshape(1, -1)

# Scale input
user_data_scaled = scaler.transform(user_data)

# Predict
prediction = model.predict(user_data_scaled)

# Output result
if prediction[0] == 1:
    print("\n✅ The model predicts: This person is likely to get a promotion.")
else:
    print("\n❌ The model predicts: This person is NOT likely to get a promotion.")


❌ The model predicts: This person is NOT likely to get a promotion.


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


# HYPER PARAMETER TUNING

In [34]:
model_params = {
    
    "Logistic Regression": {
        "model": LogisticRegression(max_iter=500),
        "params": {
            "C": [0.1, 1, 10],                     # default = 1.0
            "penalty": ["l2"],                    # default = 'l2'
            "solver": ["lbfgs", "liblinear"]      # default = 'lbfgs'
            # max_iter default = 100
        }
    },

    "Gaussian Naive Bayes": {
        "model": GaussianNB(),
        "params": {
            "var_smoothing": [1e-09, 1e-08, 1e-07]  # default = 1e-9
        }
    },

    "Decision Tree": {
        "model": DecisionTreeClassifier(random_state=42),
        "params": {
            "criterion": ["gini", "entropy"],       # default = 'gini'
            "max_depth": [3, 5, 10],                # default = None
            "min_samples_split": [2, 5, 10]         # default = 2
        }
    },

    "KNN (k=15)": {
        "model": KNeighborsClassifier(),
        "params": {
            "n_neighbors": [5, 10, 15],             # default = 5
            "weights": ["uniform", "distance"],     # default = 'uniform'
            "p": [1, 2]                              # default = 2 (Euclidean)
        }
    },

    "SVM": {
        "model": SVC(),
        "params": {
            "C": [1, 10, 20],                       # default = 1.0
            "kernel": ["rbf", "linear"],            # default = 'rbf'
            "gamma": ["auto", "scale"]              # default = 'scale'
        }
    },

    "Random Forest": {
        "model": RandomForestClassifier(),
        "params": {
            "n_estimators": [50, 100, 200],         # default = 100
            "criterion": ["gini", "entropy"],       # default = 'gini'
            "max_depth": [None, 5, 10]              # default = None
        }
    },

    "AdaBoost": {
        "model": AdaBoostClassifier(),
        "params": {
            "n_estimators": [50, 100, 200],         # default = 50
            "learning_rate": [0.5, 1.0, 2.0],       # default = 1.0
            "algorithm": ["SAMME", "SAMME.R"]       # default = 'SAMME.R'
        }
    },

    "Gradient Boosting": {
        "model": GradientBoostingClassifier(),
        "params": {
            "n_estimators": [50, 100],              # default = 100
            "learning_rate": [0.05, 0.1, 0.2],      # default = 0.1
            "max_depth": [2, 3, 5]                  # default = 3
        }
    }
}


In [35]:
# Run GridSearchCV for all models
scores = []

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp["model"], mp["params"], cv=5, return_train_score=True)
    clf.fit(X_train, y_train)

    scores.append({
        "model": model_name,
        "best_score": clf.best_score_,
        "best_params": clf.best_params_
    })

# Convert to DataFrame
df = pd.DataFrame(scores)



C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The parameter 'algorithm' is deprecated in 1.6 and has no effect. It will be removed in version 1.8.
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The parameter 'algorithm' is deprecated in 1.6 and has no effect. It will be removed in version 1.8.
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The parameter 'algorithm' is deprecated in 1.6 and has no effect. It will be removed in version 1.8.
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The parameter 'algorithm' is deprecated in 1.6 and has no effect. It will be removed in version 1.8.
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The parameter 'algorithm' is

In [36]:
pd.set_option("display.max_colwidth", None)
df


model  best_score  \
0   Logistic Regression      0.5250   
1  Gaussian Naive Bayes      0.4125   
2         Decision Tree      0.5375   
3            KNN (k=15)      0.4500   
4                   SVM      0.5125   
5         Random Forest      0.5000   
6              AdaBoost      0.5125   
7     Gradient Boosting      0.5000   

                                                         best_params  
0                     {'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'}  
1                                           {'var_smoothing': 1e-09}  
2  {'criterion': 'entropy', 'max_depth': 5, 'min_samples_split': 10}  
3                  {'n_neighbors': 10, 'p': 2, 'weights': 'uniform'}  
4                      {'C': 1, 'gamma': 'auto', 'kernel': 'linear'}  
5   {'criterion': 'entropy', 'max_depth': None, 'n_estimators': 200}  
6  {'algorithm': 'SAMME', 'learning_rate': 0.5, 'n_estimators': 200}  
7       {'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 100}

# SAVING MODEL

In [15]:
import pickle

# Save the scaler
with open('promotion_scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

# Save the model
with open('promotion_model.pkl', 'wb') as f:
    pickle.dump(model, f)
